server:
  port: 8889

spring:
  datasource:
    url: jdbc:h2:mem:jpadb
    username:
    password:
    driverClassName: org.h2.Driver
  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/static/flowable-modeler
flowable:
  #关闭定时任务JOB
  async-executor-activate: false